### ISSUE TITLE
App getting crash

### ISSUE THREAD

**Issue by ankur-dev** [carloscj6/SampleMusicPlayer#1]
Process: com.revosleap.samplemusicplayer, PID: 3773
   java.lang.RuntimeException: Unable to stop service com.revosleap.samplemusicplayer.playback.MusicService@fcf3e90: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.revosleap.samplemusicplayer.playback.MediaPlayerHolder.registerNotificationActionsReceiver(boolean)' on a null object reference

**Comment by carloscj6** [comment]
When does this issue happen?

**Comment by carloscj6** [comment]
Please check the latest code update. I have to close this for now.

**Comment by masudr4n4** [comment]
How can i download the app?
