### ISSUE TITLE
Issue while play and pause music in MainActivity

### ISSUE THREAD

**Issue by abcdna** [carloscj6/SampleMusicPlayer#2]
Hello ,
 I have download these code and run . but when I was pause song next song will be played . Please help. From notification bar its running perfect but from the mainactivity I have an issue . Please help!.

**Comment by aasif1297** [comment]
> Hello ,
> I have download these code and run . but when I was pause song next song will be played . Please help. From notification bar its running perfect but from the mainactivity I have an issue . Please help!.

on line number 267 of MainActivity there is a onClick method. Navigate there and use break; statement in every case.

**Comment by carloscj6** [comment]
Thanks, @aasif1297  for the awesome assistance. I've been away.
