### ISSUE TITLE
Seekbar progress not load in android 6

### ISSUE THREAD

**Issue by getyoteamsolutions** [carloscj6/SampleMusicPlayer#3]
When I play song seekbar onPositionChanged() method called One or Two times and then not called it. Don't know what happens with a code
I think this method not called 
Executors.newSingleThreadScheduledExecutor(); this will called one when class loaded.
https://github.com/carloscj6/SampleMusicPlayer/blob/7dd1ffbf9576be9a0bc47f564e859c0489187fa0/app/src/main/java/com/revosleap/samplemusicplayer/playback/MediaPlayerHolder.java#L224

**Comment by getyoteamsolutions** [comment]
if I write below code  behalf of this code Executors.newSingleThreadScheduledExecutor();
`if (mSeekbarUpdateHandler == null) {
            mSeekbarUpdateHandler = new Handler();
        }
            mUpdateSeekbar = new Runnable() {
                @Override
                public void run() {
                    updateProgressCallbackTask();
                    mSeekbarUpdateHandler.postDelayed(mUpdateSeekbar, 50);
                }
            };
            mSeekbarUpdateHandler.postDelayed(mUpdateSeekbar, 0)`
        
This code working fine

**Comment by carloscj6** [comment]
I have tried without your mod it works on Android 6
